services:
  eureka-service:
    container_name: eureka-service
    build:
      dockerfile: Dockerfile
      args:
        - ARTIFACT_DIRECTORY=./service/eureka-artifact
        - FILE_DIRECTORY=./service/eureka/server
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/eureka
    ports:
      - "19090:19090"

  gateway:
    container_name: gateway-service
    build:
      dockerfile: Dockerfile
      args:
        - ARTIFACT_DIRECTORY=./service/gateway-artifact
        - FILE_DIRECTORY=./service/gateway/server
    depends_on:
      - eureka-service
    ports:
      - "19091:19091"
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/gateway

  user:
    container_name: user-service
    build:
      dockerfile: Dockerfile
      args:
        - ARTIFACT_DIRECTORY=./service/user-artifact
        - FILE_DIRECTORY=./service/user/server
    depends_on:
      - eureka-service
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/user

  auth:
    container_name: auth-service
    build:
      dockerfile: Dockerfile
      args:
        - ARTIFACT_DIRECTORY=./service/auth-artifact
        - FILE_DIRECTORY=./service/auth/server
    depends_on:
      - eureka-service
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/auth

  order:
    container_name: order-service
    build:
      dockerfile: Dockerfile
      args:
        - ARTIFACT_DIRECTORY=./service/order-artifact
        - FILE_DIRECTORY=./service/order/server
    depends_on:
      - eureka-service
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/order

  cart-cache:
    container_name: cart-cache
    image: redis:7.4.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - sasaping-network

volumes:
  redis-data:

networks:
  sasaping-network:
    driver: bridge
