services:
  eureka-service:
    container_name: eureka-service
    build:
      dockerfile: Dockerfile-prod
      args:
        - ARTIFACT_DIRECTORY=./service/eureka-artifact
        - FILE_DIRECTORY=./service/eureka/server
    networks:
      - app-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/eureka
    ports:
      - "19090:19090"

  gateway:
    container_name: gateway-service
    build:
      dockerfile: Dockerfile-prod
      args:
        - ARTIFACT_DIRECTORY=./service/gateway-artifact
        - FILE_DIRECTORY=./service/gateway/server
    depends_on:
      - eureka-service
    ports:
      - "19091:19091"
    networks:
      - app-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/gateway

  user:
    container_name: user-service
    build:
      dockerfile: Dockerfile-prod
      args:
        - ARTIFACT_DIRECTORY=./service/user-artifact
        - FILE_DIRECTORY=./service/user/server
    depends_on:
      - eureka-service
    networks:
      - app-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/user

  auth:
    container_name: auth-service
    build:
      dockerfile: Dockerfile-prod
      args:
        - ARTIFACT_DIRECTORY=./service/auth-artifact
        - FILE_DIRECTORY=./service/auth/server
    depends_on:
      - eureka-service
    networks:
      - app-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/auth

#  user_db:
#    image: mysql:8.0
#    container_name: mysql_user_db
#    environment:
#      MYSQL_ROOT_PASSWORD: root_password
#      MYSQL_DATABASE: user
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    networks:
#      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
