x-build-args:
  dockerfile_name: &dockerfile_name Dockerfile-prod

services:
  eureka-service:
    container_name: eureka-service
    build:
      dockerfile: *dockerfile_name
      args:
        - ARTIFACT_DIRECTORY=./service/eureka-artifact
        - FILE_DIRECTORY=./service/eureka/server
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/eureka
    ports:
      - "19090:19090"

  gateway:
    container_name: gateway-service
    build:
      dockerfile: *dockerfile_name
      args:
        - ARTIFACT_DIRECTORY=./service/gateway-artifact
        - FILE_DIRECTORY=./service/gateway/server
    depends_on:
      - eureka-service
    ports:
      - "19091:19091"
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/gateway

  user:
    container_name: user-service
    build:
      dockerfile: *dockerfile_name
      args:
        - ARTIFACT_DIRECTORY=./service/user-artifact
        - FILE_DIRECTORY=./service/user/server
    depends_on:
      - eureka-service
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/user

  auth:
    container_name: auth-service
    build:
      dockerfile: *dockerfile_name
      args:
        - ARTIFACT_DIRECTORY=./service/auth-artifact
        - FILE_DIRECTORY=./service/auth/server
    depends_on:
      - eureka-service
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/auth

  order:
    container_name: order-service
    build:
      dockerfile: *dockerfile_name
      args:
        - ARTIFACT_DIRECTORY=./service/order-artifact
        - FILE_DIRECTORY=./service/order/server
    depends_on:
      - eureka-service
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/order

  cart-cache:
    container_name: cart-cache
    image: redis:7.4.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - sasaping-network

  payment:
    container_name: payment-service
    build:
      dockerfile: *dockerfile_name
      args:
        - ARTIFACT_DIRECTORY=./service/payment-artifact
        - FILE_DIRECTORY=./service/payment/server
    depends_on:
      - eureka-service
    ports:
      - "19061:19061"
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/payment

  slack:
    container_name: slack-service
    build:
      dockerfile: *dockerfile_name
      args:
        - ARTIFACT_DIRECTORY=./service/slack-artifact
        - FILE_DIRECTORY=./service/slack/server
    depends_on:
      - eureka-service
    networks:
      - sasaping-network
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/slack

  zookeeper:
    image: wurstmeister/zookeeper:latest
    platform: linux/amd64
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - sasaping-network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    platform: linux/amd64
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - sasaping-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis-data:

networks:
  sasaping-network:
    driver: bridge
