global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'eureka-services'
    eureka_sd_configs:
      - server: 'http://host.docker.internal:19090/eureka'   # Eureka 서버 주소
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [ '__meta_eureka_app_name' ]
        target_label: 'job'
      - source_labels: [ '__meta_eureka_instance_ip_addr' ]
        target_label: 'instance'
      - source_labels: [ '__meta_eureka_app_instance_status' ]
        action: keep
        regex: 'UP'  # 서비스 상태가 "UP"인 인스턴스만 스크랩