@Port=19091

### 로그인
POST http://localhost:{{Port}}/api/auth/sign-in
Content-Type: application/json

{
  "username": "newUser",
  "password": "password123"
}
> {%
  client.global.set("access_token", "Bearer " + response.body.data.token);
%}

### 이벤트 쿠폰 생성
POST http://localhost:{{Port}}/api/coupons/event
Content-Type: application/json
Authorization: {{access_token}}

{
  "name": "Test Coupon",
  "type": "EVENT",
  "discountType": "PRICE",
  "discountValue": 1000.00,
  "minBuyPrice": null,
  "maxDiscountPrice": null,
  "quantity": 100,
  "startDate": "2024-01-01T00:00:00",
  "endDate": "2024-12-31T23:59:59",
  "userTier": null,
  "eventId": 1
}

### 이벤트 쿠폰 발급
@couponId=1
POST http://localhost:{{Port}}/api/coupons/event/{{couponId}}
Authorization: {{access_token}}

### 쿠폰 전체 조회
GET http://localhost:{{Port}}/api/coupons
Authorization: {{access_token}}

### 쿠폰 단일 조회
GET http://localhost:{{Port}}/api/coupons/{{couponId}}
Authorization: {{access_token}}

### 특정 사용자 쿠폰 전체 조회
@userId=11
GET http://localhost:{{Port}}/api/coupons/users/{{userId}}
Authorization: {{access_token}}
