@Port=19091
@TokenUser=Bearer eyJhbGciOiJIUzI1NiJ9.eyJVU0VSX05BTUUiOiJuZXdVc2VyMiIsIlVTRVJfUk9MRSI6IlJPTEVfVVNFUiIsIlVTRVJfSUQiOjEwLCJpYXQiOjE3Mjg4Mjk4MjMsImV4cCI6MTczMjQyOTgyM30.E1Tzyf9TUh7sWeFKnBfz_W_1xd_MR-WgBw0VRgDCXO4
@TokenAdmin=Bearer eyJhbGciOiJIUzI1NiJ9.eyJVU0VSX0lEIjoxMSwiVVNFUl9ST0xFIjoiUk9MRV9BRE1JTiIsIlVTRVJfTkFNRSI6Im5ld1VzZXIiLCJpYXQiOjE3Mjg2NTYxMjUsImV4cCI6MTczMjI1NjEyNX0.z_M-s8XwM2SKA7ojdNR9ZoMRd7isn8VLlKmL0i5iI4s

### 회원가입
POST http://localhost:{{Port}}/api/users/sign-up
Content-Type: application/json

{
  "username": "newUser5",
  "password": "password123",
  "nickname": "nickname5",
  "role": "관리자"
}

### 마이페이지 조회
GET http://localhost:{{Port}}/api/users/me
Authorization: {{TokenUser}}

### 인증/인가 테스트 API
GET http://localhost:{{Port}}/api/users/hello
Authorization: {{TokenAdmin}}
