@Port=19091
@Token=Bearer eyJhbGciOiJIUzI1NiJ9.eyJVU0VSX1JPTEUiOiJST0xFX0FETUlOIiwiVVNFUl9JRCI6NywiVVNFUl9OQU1FIjoibmV3VXNlciIsImlhdCI6MTcyODI5MjM2NywiZXhwIjoxNzMxODkyMzY3fQ.Kvp1JJLpjxjRX4N8Nt46QP-_1jAnSzVvSISordEMHN8

### 회원가입
POST http://localhost:{{Port}}/api/users/sign-up
Content-Type: application/json

{
  "username": "newUser",
  "password": "password123",
  "nickname": "nickname",
  "point": 0,
  "role": "관리자"
}

### 인증/인가 테스트 API
GET http://localhost:{{Port}}/api/users/hello
Authorization: {{Token}}
