server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**

        - id: user
          uri: lb://user
          predicates:
            - Path=/api/users/**, /api/tier/**

        - id: product
          uri: lb://product
          predicates:
            - Path=/api/products/**, /api/preproducts/**, /api/categories/**,

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
