spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sasaping-database.ctem8i2eavmt.ap-northeast-2.rds.amazonaws.com:3306/product
    username: sasaping
    password: ${DB_PASSWORD}

  cassandra:
    contact-points: cassandra
    port: 9042
    keyspace-name: product
    schema-action: create_if_not_exists
    local-datacenter: datacenter01

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  elasticsearch:
    rest:
      host: es01
      port: 9200
      uris: http://es01:9200
    fingerprint: ${ELASTIC_FINGERPRINT}
    account: elastic
    password: ${ELASTIC_PASSWORD}

  data:
    redis:
      host: product-cache
      port: 6380

  kafka:
    bootstrap-servers: ${EC2_PUBLIC_IP}:9092
    listener:
      ack-mode: MANUAL
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: product
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

product:
  search-index: "sasaping-ecommerce-products"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:19090/eureka/
