@Port=19091

### 장바구니 상품 추가
POST http://localhost:{{Port}}/api/carts/products
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "productId": "920164fe-8906-4a51-a6b8-1683277d09b2",
  "quantity": 10
}

### 장바구니 상품 조회
GET http://localhost:{{Port}}/api/carts
Authorization: Bearer {{access_token}}

### 장바구니 상품 개수 수정
PATCH http://localhost:{{Port}}/api/carts/products
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "productId": "5052b3c6-838c-4506-b658-9ff8f59fb4da",
  "quantity": 1
}

### 장바구니 상품 삭제
DELETE http://localhost:{{Port}}/api/carts/products/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb1g?
    userId=123456
Authorization: Bearer {{access_token}}

### 장바구니 전체 삭제
DELETE http://localhost:{{Port}}/api/carts/clear?userId=123456
Authorization: Bearer {{access_token}}

### 상품 생성
POST http://localhost:19091/api/products
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "categoryId": 1,
  "productName": "Product 1",
  "brandName": "brandName",
  "mainColor": "pink",
  "size": "S",
  "originalPrice": 10000,
  "discountPercent": 50,
  "stock": 100,
  "description": "This is an example product description.",
  "thumbnailImgUrl": "http://example.com/thumbnail.jpg",
  "detailImgUrl": "http://example.com/detail.jpg",
  "limitCountPerUser": 0,
  "tags": [
    "COUPON",
    "EXPRESS_DELIVERY",
    "FREE_SHIPPING",
    "DISCOUNT",
    "NEW"
  ]
}

### 카테고리 생성
POST http://localhost:{{Port}}/api/categories
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "CLOTHES",
  "parentCategoryId": null
}
