@Port=19091

### 주문 생성
POST http://localhost:{{Port}}/api/orders
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "orderType": "STANDARD",
  "orderProductInfos": [
    {
      "productId": "19646241-55d8-40f7-8f3e-d7242dedff49",
      "quantity": 3,
      "userCouponId": 132
    }
  ],
  "pointPrice": 1,
  "addressId": 1
}

### 상품 재고 조회
GET http://localhost:{{Port}}/api/products/19646241-55d8-40f7-8f3e-d7242dedff49
Authorization: Bearer {{access_token}}
