spring:
  application:
    name: payment
  elasticsearch:
    uris: { ELASTIC_URL }
    password: { ELASTIC_PASSWORD }
    username: { ELASTIC_USER }
  datasource:
    url: { LOCAL_DB_URL }
    username: { LOCAL_DB_USERNAME }
    password: { LOCAL_DB_PASSWORD }
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 19061

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

TOSS_SECRET_KEY: { TOSS_SECRET_KEY }
