spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
