spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/prod

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:19090/eureka/
