name: CI with Gradle

on:
  pull_request:
    branches: [ dev ]

permissions:
  contents: read

jobs:
  setup:
    name: Set up environment
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

  build:
    name: Build Services
    runs-on: ubuntu-latest
    needs: setup  # 'setup' job이 완료된 후에 실행됨
    permissions: write-all
    strategy:
      matrix:
        service: [
          user/server, auth/server, gateway/server,
          notification/server, order/server, payment/server,
          product/product_server, slack/server ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Gradle
        run: ./gradlew clean build -p ./service/${{ matrix.service }} -x test
